version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.16

    steps:
      - checkout

      - run:
          name: Build
          command: go build -o mywebapp

      - run:
          name: Test
          command: go test ./...

      - persist_to_workspace:
          root: .
          paths:
            - mywebapp

  deploy:
    docker:
      - image: circleci/golang:1.16

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Deploy to GitHub
          command: |
            git config --global user.email "Fernando.mateluna@gmail.com"
            git config --global user.name "Fernando M"
            git add .
            git commit -m "Auto-deployed from CircleCI"
            git push origin master
